import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { apiGet, apiPost } from "../api/client";
import { useLLP } from "../context/LLPContext";
import { formatDate } from "../utils/format";

const card={background:"var(--card)",border:"1px solid var(--border)",borderRadius:"var(--radius)",padding:"1.25rem"};
const label={display:"block",fontSize:".75rem",color:"var(--muted)",marginBottom:".35rem",fontWeight:500};
const btn=(v="primary")=>({padding:".55rem 1rem",borderRadius:"6px",cursor:"pointer",fontWeight:600,border:v==="primary"?"none":"1px solid var(--border)",background:v==="primary"?"var(--accent)":"transparent",color:v==="primary"?"#fff":"var(--muted)"});
const input={width:"100%",boxSizing:"border-box",padding:".55rem .7rem",background:"var(--input)",color:"var(--text)",border:"1px solid var(--border)",borderRadius:"6px"};
const initial={EntryID:"",BankAccountID:"",Date:"",Type:"Receipt",Amount:"",LedgerID:"",ReferenceID:"",Description:""};
const fmt=n=>"₹"+Number(n||0).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2});

export default function Transactions(){
 const navigate=useNavigate(),{currentLLP}=useLLP();
 const[accounts,setAccounts]=useState([]),[ledgers,setLedgers]=useState([]),[transactions,setTransactions]=useState([]),[form,setForm]=useState(initial),[formOpen,setFormOpen]=useState(false),[editing,setEditing]=useState(false),[loading,setLoading]=useState(false),[search,setSearch]=useState("");
 async function load(){setLoading(true);try{const[b,l,t]=await Promise.allSettled([apiGet("getBankAccounts"),apiGet("getLedgers"),apiGet("getBankTransactions")]);if(b.status==="fulfilled"&&b.value.ok)setAccounts((b.value.data||[]).filter(x=>x.IsActive!=="No"));if(l.status==="fulfilled"&&l.value.ok)setLedgers((l.value.data||[]).filter(x=>x.Status!=="Inactive"));if(t.status==="fulfilled"&&t.value.ok)setTransactions(t.value.data||[]);}finally{setLoading(false)}}
 useEffect(()=>{load()},[currentLLP?.llpId,currentLLP?.LLPID,currentLLP?.global]);
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return !q?transactions:transactions.filter(r=>[r.BankAccountName,r.BankName,r.LedgerName,r.ReferenceID,r.Description,r.ReferenceType].some(v=>String(v||"").toLowerCase().includes(q)))},[transactions,search]);
 function openNew(type){setEditing(false);setForm({...initial,Type:type,Date:new Date().toISOString().slice(0,10)});setFormOpen(true)}
 function edit(r){if(r.Managed)return;setEditing(true);setForm({EntryID:r.EntryID,BankAccountID:r.BankAccountID||"",Date:r.Date||"",Type:Number(r.AmountIn||0)>0?"Receipt":"Payment",Amount:String(Number(r.AmountIn||0)>0?r.AmountIn:r.AmountOut||""),LedgerID:r.LedgerID||"",ReferenceID:r.ReferenceID||"",Description:r.Description||""});setFormOpen(true)}
 async function save(e){e.preventDefault();const amount=Number(form.Amount)||0;if(!form.BankAccountID||!form.LedgerID||amount<=0)return alert("Bank, Ledger and positive Amount are required");const receipt=form.Type==="Receipt";const payload={BankAccountID:form.BankAccountID,Date:form.Date,Type:form.Type,AmountIn:receipt?amount:"",AmountOut:receipt?"":amount,ReferenceType:"Ledger",ReferenceID:form.ReferenceID,Description:form.Description,LedgerID:form.LedgerID};try{if(editing)await apiPost("updateBankTransaction",{...payload,EntryID:form.EntryID});else{const r=await apiPost("saveCashEntry",payload);await apiPost("postCashToLedger",{EntryID:r.data?.EntryID,LedgerID:form.LedgerID});}setFormOpen(false);setEditing(false);setForm(initial);await load()}catch(err){alert(err.message)}}
 async function remove(r){if(r.Managed)return;if(!confirm(`Delete transaction ${r.ReferenceID||r.Description||r.EntryID}?`))return;try{await apiPost("deleteBankTransaction",{EntryID:r.EntryID});await load()}catch(err){alert(err.message)}}
 return <div style={{display:"flex",flexDirection:"column",gap:"1.25rem"}}>
  <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",flexWrap:"wrap",gap:"1rem"}}><div><h2 style={{fontSize:"1.25rem"}}>Transactions</h2><p style={{color:"var(--muted)",fontSize:".8rem"}}>Bank receipts and payments. Source-managed Payable/Reimbursement transactions are protected.</p></div><div style={{display:"flex",gap:".6rem"}}><button style={btn("ghost")} onClick={()=>openNew("Payment")}>+ Payment</button><button style={btn()} onClick={()=>openNew("Receipt")}>+ Receipt</button></div></div>
  {formOpen&&<div style={card}><form onSubmit={save}><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(210px,1fr))",gap:"1rem"}}>
   <div><label style={label}>Type</label><select style={input} value={form.Type} onChange={e=>setForm(p=>({...p,Type:e.target.value}))}><option>Receipt</option><option>Payment</option></select></div>
   <div><label style={label}>Date</label><input style={input} type="date" required value={form.Date} onChange={e=>setForm(p=>({...p,Date:e.target.value}))}/></div>
   <div><label style={label}>Bank Account</label><select style={input} required value={form.BankAccountID} onChange={e=>setForm(p=>({...p,BankAccountID:e.target.value}))}><option value="">— Select bank —</option>{accounts.map(a=><option key={a.AccountID} value={a.AccountID}>{a.AccountName} · {a.BankName} · {String(a.AccountNumber||"").slice(-4)}</option>)}</select></div>
   <div><label style={label}>Amount (₹)</label><input style={input} type="number" step=".01" min="0" required value={form.Amount} onChange={e=>setForm(p=>({...p,Amount:e.target.value}))}/></div>
   <div><label style={label}>Ledger</label><select style={input} required value={form.LedgerID} onChange={e=>e.target.value==="__NEW__"?navigate("/ledgers"):setForm(p=>({...p,LedgerID:e.target.value}))}><option value="">— Select ledger —</option>{ledgers.map(l=><option key={l.LedgerID} value={l.LedgerID}>{l.LedgerName} · {l.GroupName}</option>)}<option value="__NEW__">+ Add New Ledger</option></select></div>
   <div><label style={label}>Reference / UTR</label><input style={input} value={form.ReferenceID} onChange={e=>setForm(p=>({...p,ReferenceID:e.target.value}))}/></div>
   <div style={{gridColumn:"span 2"}}><label style={label}>Narration</label><input style={input} value={form.Description} onChange={e=>setForm(p=>({...p,Description:e.target.value}))}/></div>
  </div><div style={{display:"flex",gap:".6rem",marginTop:"1rem"}}><button style={btn()} type="submit">{editing?"Update":"Save"} Transaction</button><button style={btn("ghost")} type="button" onClick={()=>setFormOpen(false)}>Cancel</button></div></form></div>}
  <div style={card}><label style={label}>Search</label><input style={input} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Bank, ledger, reference or narration"/></div>
  <div style={{...card,padding:0,overflow:"hidden"}}><div style={{overflowX:"auto"}}>{loading?<p style={{padding:"2rem",textAlign:"center"}}>Loading...</p>:<table><thead><tr><th>Date</th><th>Type</th><th>Bank</th><th>Ledger</th><th>Amount</th><th>Reference</th><th>Narration</th><th>Source</th><th></th></tr></thead><tbody>{filtered.length?filtered.map(r=>{const receipt=Number(r.AmountIn||0)>0;const amount=receipt?r.AmountIn:r.AmountOut;return <tr key={r.EntryID}><td>{formatDate(r.Date)}</td><td style={{fontWeight:700,color:receipt?"var(--success)":"var(--danger)"}}>{receipt?"Receipt":"Payment"}</td><td>{r.BankAccountName||"—"}</td><td>{r.LedgerName||"—"}</td><td style={{fontWeight:700}}>{receipt?"+":"-"}{fmt(amount)}</td><td>{r.ReferenceID||"—"}</td><td>{r.Description||"—"}</td><td>{r.Managed?<span style={{color:"var(--accent2)",fontWeight:600}}>{r.ManagedBy}</span>:"Manual"}</td><td>{!r.Managed&&<><button style={btn("ghost")} onClick={()=>edit(r)}>Edit</button>{" "}<button style={{...btn("ghost"),color:"var(--danger)"}} onClick={()=>remove(r)}>Delete</button></>}</td></tr>}):<tr><td colSpan="9" style={{padding:"2rem",textAlign:"center",color:"var(--muted)"}}>No transactions yet.</td></tr>}</tbody></table>}</div></div>
 </div>
}
